// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Toggler_Service.Repositories;

#nullable disable

namespace Toggler_Service.Migrations
{
    [DbContext(typeof(ServiceTogglerContext))]
    partial class ServiceTogglerContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Toggler_Service.Models.Service", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("Identifier")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Services");
                });

            modelBuilder.Entity("Toggler_Service.Models.Toggle", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Toggles");
                });

            modelBuilder.Entity("Toggler_Service.Models.ToggleService", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<long>("ServiceId")
                        .HasColumnType("bigint");

                    b.Property<long>("ToggleId")
                        .HasColumnType("bigint");

                    b.Property<bool?>("Value")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("ServiceId");

                    b.HasIndex("ToggleId");

                    b.ToTable("ToggleServices");
                });

            modelBuilder.Entity("Toggler_Service.Models.ToggleService", b =>
                {
                    b.HasOne("Toggler_Service.Models.Service", "Service")
                        .WithMany("ToggleServices")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Toggler_Service.Models.Toggle", "Toggle")
                        .WithMany("ToggleServices")
                        .HasForeignKey("ToggleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Service");

                    b.Navigation("Toggle");
                });

            modelBuilder.Entity("Toggler_Service.Models.Service", b =>
                {
                    b.Navigation("ToggleServices");
                });

            modelBuilder.Entity("Toggler_Service.Models.Toggle", b =>
                {
                    b.Navigation("ToggleServices");
                });
#pragma warning restore 612, 618
        }
    }
}
